### ISSUE TITLE
i have an xbox 360 WT and LP and would like to know which pcb to use for strum bar

### ISSUE THREAD

**Issue by Ll3ma** [Pixelholic/strum-pcbs#1]
the 360 guitars are odd and the strum bar is just a pcb that connects to the mainboard, which pcb design should i use

**Comment by Pixelholic** [comment]
Sorry for the late reply. The LP board works for all LPs. The Wii one is the most annoying, cuz all of the logic is on the strum PCB.

**Comment by Ll3ma** [comment]
> Sorry for the late reply. The LP board works for all LPs. The Wii one is the most annoying, cuz all of the logic is on the strum PCB.

what about the world tour?
